### ISSUE TITLE
Error on make all

### ISSUE THREAD

**Issue by digimatt22** [area-8051/uni-STC#4]
First I want to thank you for the great project you have put together.  In using it I have come across the following behavior:

After running make clean and then running make all I get the following error:

/Users/mwood/Documents/DigiColony/uni-STC/makefiles/2-mcu-rules.mk:34: target `build' given more than once in the same rule.
sed: 1: "build/dependencies.mk": undefined label 'uild/dependencies.mk'
make: *** No rule to make target `build/dependencies.mk', needed by `all'.  Stop.

If I run make all again it appears to work properly.  Is there a way to prevent this requirement?

**Comment by area-8051** [comment]
Thank you for the compliment, and for reporting this bug.
It was caused by the unnecessary duplication of the build directory in a rule.
For some reason, my version of make (GNU Make 4.3) didn't issue an error.
Anyway, it's fixed and committed. :)

**Comment by digimatt22** [comment]
Thank you for looking at this.  With the above change I still saw an issue however.  I spent a little time digging into the error message and have found since I am using a OSX system that sed works a little differently.  The -I parameter requires an extension for the backup file.  Updating the sed command in 2-mcu-rules.mk appear to correct the problem on my OSX system.  I can create a branch and submit a pull request if that is your preference but I don't have a linux system to test on at the moment. 

@sed -i "s/^\(.*\.rel:.*\)/build\/\1/g" $(DEP_FILE) -> @sed -i ".bak" "s/^\(.*\.rel:.*\)/build\/\1/g" $(DEP_FILE)

**Comment by area-8051** [comment]
Ah, it's a BSD sed. Does it work if you use -i '' or -i'' (two single quotes with or without space between -i and '')?

**Comment by area-8051** [comment]
Oh, and what does "sed --version" print?
I'd like to add code to detect if we're using GNU sed or not.

**Comment by digimatt22** [comment]
That appears to be an invalid command on OSX sed which appears to be FreeBSD sed from 2005 vs GNU sed.  I don't know if it's something that you can auto detect or if you just provide alternate OSX versions or even just note it.  Which rules to include could be controlled by the end user in their make file to account for the difference.

**Comment by digimatt22** [comment]
In regards to your other question, -i '' does work.

**Comment by area-8051** [comment]
It should work on both MacOS and Linux, now. :)

**Comment by digimatt22** [comment]
This appears to be working.  Thank You!
